### ISSUE TITLE
NSTabView not supported in XIB decoding.

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#67] opened 2020-07-03 11:36 UTC
The tabview items are not decoding when the XIB is unarchived.  Thus we end up with an ugly empty tabview.

Steps to recreate: 

1) Create a XIB with an NSTabView in XCode and give it multiple tabs with varying contents.
2) Bring the project onto a GNUstep machine
3) build the project with libs-xcode and buildtool.
4) run the project

Expected: The tab vies should show up.
Actual: only the box of the tabview is drawn.  No items and no tabs are shown

GC

**Comment by fredkiefer** [comment] 2020-07-03 12:21
If you provide a XIB file showing this behaviour I am willing to fix this issue.

**Comment by gcasa** [comment] 2020-07-03 14:07
> If you provide a XIB file showing this behaviour I am willing to fix this issue.

Sure, one sec....   

Please clone the repo here... https://github.com/gcasa/NSTabView_test

It produces this... 
![tab_view_example](https://user-images.githubusercontent.com/27943/86476676-f96eb880-bd14-11ea-94bd-cf109467fc61.png)

It should have two tabs, one with a button in it and one with a scrollview.

**Comment by gcasa** [comment] 2020-07-03 14:16
Thanks, Fred.  Much appreciated.

**Comment by gcasa** [comment] 2020-07-03 14:19
Just for completeness...

![mac_tab_view](https://user-images.githubusercontent.com/27943/86477564-ae55a500-bd16-11ea-860a-ccac7c048148.png)

**Comment by fredkiefer** [comment] 2020-07-03 15:07
I am a bit confused here. Leaving away the menu your XIB file looks like this:

      <window title="NSTabView_test" allowsToolTipsWhenApplicationIsInactive="NO" autorecalculatesKeyViewLoop="NO" releasedWhenClosed="NO" animationBehavior="default" id="QvC-M9-y7g">
            <windowStyleMask key="styleMask" titled="YES" closable="YES" miniaturizable="YES" resizable="YES"/>
            <windowPositionMask key="initialPositionMask" leftStrut="YES" rightStrut="YES" topStrut="YES" bottomStrut="YES"/>
            <rect key="contentRect" x="335" y="390" width="480" height="360"/>
            <rect key="screenRect" x="0.0" y="0.0" width="1680" height="1027"/>
            <view key="contentView" id="EiT-Mj-1SZ">
                <rect key="frame" x="0.0" y="0.0" width="480" height="360"/>
                <autoresizingMask key="autoresizingMask"/>
            </view>
        </window>

I don't see how this would ever result in an NSTab being displayed. And in the application code I find a lot of stuff about NSPersistentContainer, which may or may not work with GNUstep but it surely is not related to NSTab. Could you please provide me with the XIB file you use on Mac and maybe even check if the issue exists when using that XIB file?

**Comment by gcasa** [comment] 2020-07-03 15:14
I understand your confusion.  I had to recreate the repo last night and FORGOT to push.  Please check now....  The new xib does contain the relevant data...

```
        <window title="NSTabView_test" allowsToolTipsWhenApplicationIsInactive="NO" autorecalculatesKeyViewLoop="NO" releasedWhenClosed="NO" animationBehavior="default" id="QvC-M9-y7g">
            <windowStyleMask key="styleMask" titled="YES" closable="YES" miniaturizable="YES" resizable="YES"/>
            <windowPositionMask key="initialPositionMask" leftStrut="YES" rightStrut="YES" topStrut="YES" bottomStrut="YES"/>
            <rect key="contentRect" x="335" y="390" width="480" height="360"/>
            <rect key="screenRect" x="0.0" y="0.0" width="2048" height="1129"/>
            <view key="contentView" id="EiT-Mj-1SZ">
                <rect key="frame" x="0.0" y="0.0" width="480" height="360"/>
                <autoresizingMask key="autoresizingMask"/>
                <subviews>
                    <tabView fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="QaP-hi-LfH">
                        <rect key="frame" x="13" y="8" width="454" height="338"/>
                        <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                        <font key="font" metaFont="system"/>
                        <tabViewItems>
                            <tabViewItem label="Tab" identifier="" id="HoT-4f-oDp">
                                <view key="view" id="dW7-db-w0A">
                                    <rect key="frame" x="10" y="33" width="434" height="292"/>
                                    <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                                    <subviews>
                                        <button verticalHuggingPriority="750" fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="zYR-02-FXy">
                                            <rect key="frame" x="74" y="157" width="81" height="32"/>
                                            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                                            <buttonCell key="cell" type="push" title="Button" bezelStyle="rounded" alignment="center" borderStyle="border" imageScaling="proportionallyDown" inset="2" id="2eh-Pb-994">
                                                <behavior key="behavior" pushIn="YES" lightByBackground="YES" lightByGray="YES"/>
                                                <font key="font" metaFont="system"/>
                                            </buttonCell>
                                        </button>
                                        <button verticalHuggingPriority="750" fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="QDo-cb-7l3">
                                            <rect key="frame" x="261" y="157" width="81" height="32"/>
                                            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                                            <buttonCell key="cell" type="push" title="Button" bezelStyle="rounded" alignment="center" borderStyle="border" imageScaling="proportionallyDown" inset="2" id="c6C-Y5-LuS">
                                                <behavior key="behavior" pushIn="YES" lightByBackground="YES" lightByGray="YES"/>
                                                <font key="font" metaFont="system"/>
                                            </buttonCell>
                                        </button>
                                    </subviews>
                                </view>
                            </tabViewItem>
                            <tabViewItem label="View" identifier="" id="WGV-e6-fkn">
                                <view key="view" id="6Qn-q9-6ag">
                                    <rect key="frame" x="10" y="33" width="434" height="292"/>
                                    <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                                    <subviews>
                                        <scrollView fixedFrame="YES" borderType="none" horizontalLineScroll="10" horizontalPageScroll="10" verticalLineScroll="10" verticalPageScroll="10" hasHorizontalScroller="NO" translatesAutoresizingMaskIntoConstraints="NO" id="d8R-vs-bcp">
                                            <rect key="frame" x="35" y="40" width="240" height="135"/>
                                            <autoresizingMask key="autoresizingMask"/>
                                            <clipView key="contentView" drawsBackground="NO" copiesOnScroll="NO" id="amE-s9-wmg">
                                                <rect key="frame" x="0.0" y="0.0" width="225" height="135"/>
                                                <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                                                <subviews>
                                                    <textView importsGraphics="NO" richText="NO" verticallyResizable="YES" spellingCorrection="YES" smartInsertDelete="YES" id="VJU-JT-x7g">
                                                        <rect key="frame" x="0.0" y="0.0" width="225" height="135"/>
                                                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                                                        <color key="textColor" name="textColor" catalog="System" colorSpace="catalog"/>
                                                        <color key="backgroundColor" name="textBackgroundColor" catalog="System" colorSpace="catalog"/>
                                                        <size key="minSize" width="225" height="135"/>
                                                        <size key="maxSize" width="225" height="10000000"/>
                                                        <color key="insertionPointColor" name="textColor" catalog="System" colorSpace="catalog"/>
                                                    </textView>
                                                </subviews>
                                            </clipView>
                                            <scroller key="horizontalScroller" hidden="YES" verticalHuggingPriority="750" horizontal="YES" id="eDm-nA-ChB">
                                                <rect key="frame" x="-100" y="-100" width="225" height="15"/>
                                                <autoresizingMask key="autoresizingMask"/>
                                            </scroller>
                                            <scroller key="verticalScroller" verticalHuggingPriority="750" horizontal="NO" id="oU6-ZF-hpR">
                                                <rect key="frame" x="225" y="0.0" width="15" height="135"/>
                                                <autoresizingMask key="autoresizingMask"/>
                                            </scroller>
                                        </scrollView>
                                    </subviews>
                                </view>
                            </tabViewItem>
                        </tabViewItems>
                    </tabView>
                </subviews>
            </view>
            <point key="canvasLocation" x="132" y="-120"/>
        </window>
    </objects>
</document>
```

**Comment by fredkiefer** [comment] 2020-07-03 16:08
Now with a file that actually shows this behaviour it was easy to see the cause. In the alternateName: method we sometimes chop of too much from the name. Fixing this is harder though as I don't want to add another special case handling. I will try to figure out a general rule to apply here.

**Comment by gcasa** [comment] 2020-07-03 16:54
> Now with a file that actually shows this behaviour it was easy to see the cause. In the alternateName: method we sometimes chop of too much from the name. Fixing this is harder though as I don't want to add another special case handling. I will try to figure out a general rule to apply here.

Okay, cool.  I'm ready to test and review whenever you're done.  Thanks for your patience.

**Comment by fredkiefer** [comment] 2020-07-03 17:38
I committed a small change to master that should fix the issue.

**Closed by fredkiefer** 2020-07-03 17:38 UTC

**Comment by gcasa** [comment] 2020-07-03 19:43
Tested and working.  Thanks.
