### ISSUE TITLE
NSCircularBezelStyle should cut text 

### ISSUE THREAD

**Issue by optimisme** [gnustep/libs-gui#224] opened 2023-12-22 10:48 UTC
NSCircularBezelStyle should cut text if necessary

The image on the left shows 'GNUStep' interpretation of the circular bezel style with the text 'Circular' but the image on the right is the desired visualization only showing 'Ci'

<img width="1470" alt="Screenshot 2023-12-22 at 11 45 41" src="https://github.com/gnustep/libs-gui/assets/7429620/60a14c2b-257a-4cd1-8768-e171e1807094">

**Comment by gcasa** [comment] 2023-12-22 19:45
![GNUstepCircularButton](https://github.com/gnustep/libs-gui/assets/27943/c2693bc6-55b4-4665-9e6d-c147900e2a77)
The above is how the default theme draws it...  while this is likely incorrect since it STRETCHES the circle I am not sure where the behavior you're seeing is coming from.

The image on the left is NOT GNUstep or it is at the very least a THEME on GNUstep.   Either way, and I asked this before, what theme or OS are you using to produce the images you're presenting?   This is not a denial of any issue on our part... merely a request for complete information.

**Comment by gcasa** [comment] 2023-12-22 19:46
Please help me understand.... the reason I am asking is that it would be helpful to load the theme you're using and see precisely where either GS or the theme are going wrong.  Thx

**Comment by gcasa** [comment] 2023-12-22 19:50
Also, can you attach a test program that illustrates what you're seeing above.  (hopefully the one you're using)

**Comment by optimisme** [comment] 2023-12-22 23:39
In my image, the left one (the wrong one) comes from this theme (in development)
https://github.com/optimisme/GNUStep-Theme
the right image comres from the same application rendered by macOS

**Comment by fredkiefer** [comment] 2023-12-23 22:44
This is rather an issue in your own theme. The code there does not inset the frame of the menu item cell to the frame left inside of the circle. Please have a look at the code inside of GSThemeDrawing.m in GNUstep. There you can see how the variable frame gets adjusted.
I will close this issue as it is not caused by GNUstep itself.

**Closed by fredkiefer** 2023-12-23 22:44 UTC
Labels: bug
