### ISSUE TITLE
Controls not loading correctly on G5 (BigEndian 64bit)

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-gui#89] opened 2021-01-07 20:54 UTC
Standard Print Panel (Ink)
* printer list and Layout contain (item1, item2, item3) as coming from gorm
* Copies and Scale contain "Text" and not correct value
* Clicking "options" button does not open the options panel but closes print panel

![printpanel_g5_bug](https://user-images.githubusercontent.com/12441935/103943836-0c829b00-5133-11eb-85a8-f3404c6fc017.png)

**Comment by rmottola** [comment] 2021-01-13 21:09
All issues above can be reproduced on Sparc64/NetBSD - plus that has also color issues with font display!

**Comment by fredkiefer** [comment] 2021-01-15 21:50
I think most of these issues where caused by NSControl not decoding the tag correctly. The values get set at runtime via the tag of the subviews. I corrected that decoding. Please give it another try.

**Comment by fredkiefer** [comment] 2021-01-22 14:00
Closed as all issues were reported as resolved on the mailing list.

**Closed by fredkiefer** 2021-01-22 14:00 UTC
